
server:
  port: 5001

spring:
  application:
    name: service-zuul

#zuul:
#  routes:
#    baidu:
#      url: http://www.baidu.com
#      path: /api/**

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.133:9000/eureka/